// ISO-style flag emoji map for World Cup 2026 nations.
// Names match openfootball/worldcup.json exactly.
export const FLAGS: Record<string, string> = {
  "Argentina": "🇦🇷",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Algeria": "🇩🇿",
  "Belgium": "🇧🇪",
  "Bosnia & Herzegovina": "🇧🇦",
  "Brazil": "🇧🇷",
  "Canada": "🇨🇦",
  "Cape Verde": "🇨🇻",
  "Colombia": "🇨🇴",
  "Croatia": "🇭🇷",
  "Curaçao": "🇨🇼",
  "Czech Republic": "🇨🇿",
  "Denmark": "🇩🇰",
  "DR Congo": "🇨🇩",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Haiti": "🇭🇹",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Italy": "🇮🇹",
  "Ivory Coast": "🇨🇮",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Mexico": "🇲🇽",
  "Morocco": "🇲🇦",
  "Netherlands": "🇳🇱",
  "New Zealand": "🇳🇿",
  "Norway": "🇳🇴",
  "Panama": "🇵🇦",
  "Paraguay": "🇵🇾",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Saudi Arabia": "🇸🇦",
  "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "Senegal": "🇸🇳",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Spain": "🇪🇸",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Tunisia": "🇹🇳",
  "Turkey": "🇹🇷",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Uzbekistan": "🇺🇿",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};

export function flag(name: string): string {
  return FLAGS[name] ?? "🏳️";
}

// ISO 3166-1 alpha-2 codes (plus GB regional codes) for country-flag-icons.
export const FLAG_CODES: Record<string, string> = {
  "Argentina": "AR",
  "Australia": "AU",
  "Austria": "AT",
  "Algeria": "DZ",
  "Belgium": "BE",
  "Bosnia & Herzegovina": "BA",
  "Brazil": "BR",
  "Canada": "CA",
  "Cape Verde": "CV",
  "Colombia": "CO",
  "Croatia": "HR",
  "Curaçao": "CW",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "DR Congo": "CD",
  "Ecuador": "EC",
  "Egypt": "EG",
  "England": "GB-ENG",
  "France": "FR",
  "Germany": "DE",
  "Ghana": "GH",
  "Haiti": "HT",
  "Iran": "IR",
  "Iraq": "IQ",
  "Italy": "IT",
  "Ivory Coast": "CI",
  "Japan": "JP",
  "Jordan": "JO",
  "Mexico": "MX",
  "Morocco": "MA",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Norway": "NO",
  "Panama": "PA",
  "Paraguay": "PY",
  "Poland": "PL",
  "Portugal": "PT",
  "Qatar": "QA",
  "Saudi Arabia": "SA",
  "Scotland": "GB-SCT",
  "Senegal": "SN",
  "South Africa": "ZA",
  "South Korea": "KR",
  "Spain": "ES",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Tunisia": "TN",
  "Turkey": "TR",
  "United States": "US",
  "USA": "US",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Wales": "GB-WLS",
};

export function flagCode(name: string): string | undefined {
  return FLAG_CODES[name];
}