/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedPredictionsRouteImport } from './routes/_authenticated/predictions'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedFuturesRouteImport } from './routes/_authenticated/futures'
import { Route as AuthenticatedFixturesRouteImport } from './routes/_authenticated/fixtures'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedVeikkaaIndexRouteImport } from './routes/_authenticated/veikkaa.index'
import { Route as AuthenticatedFixturesIndexRouteImport } from './routes/_authenticated/fixtures.index'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'
import { Route as AuthenticatedVeikkaaMatchIdRouteImport } from './routes/_authenticated/veikkaa.$matchId'
import { Route as AuthenticatedTeamsTeamRouteImport } from './routes/_authenticated/teams.$team'
import { Route as AuthenticatedFixturesMatchIdRouteImport } from './routes/_authenticated/fixtures.$matchId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPredictionsRoute =
  AuthenticatedPredictionsRouteImport.update({
    id: '/predictions',
    path: '/predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuturesRoute = AuthenticatedFuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFixturesRoute = AuthenticatedFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVeikkaaIndexRoute =
  AuthenticatedVeikkaaIndexRouteImport.update({
    id: '/veikkaa/',
    path: '/veikkaa/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFixturesIndexRoute =
  AuthenticatedFixturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFixturesRoute,
  } as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVeikkaaMatchIdRoute =
  AuthenticatedVeikkaaMatchIdRouteImport.update({
    id: '/veikkaa/$matchId',
    path: '/veikkaa/$matchId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamsTeamRoute = AuthenticatedTeamsTeamRouteImport.update({
  id: '/$team',
  path: '/$team',
  getParentRoute: () => AuthenticatedTeamsRoute,
} as any)
const AuthenticatedFixturesMatchIdRoute =
  AuthenticatedFixturesMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => AuthenticatedFixturesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fixtures': typeof AuthenticatedFixturesRouteWithChildren
  '/futures': typeof AuthenticatedFuturesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/fixtures/$matchId': typeof AuthenticatedFixturesMatchIdRoute
  '/teams/$team': typeof AuthenticatedTeamsTeamRoute
  '/veikkaa/$matchId': typeof AuthenticatedVeikkaaMatchIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/fixtures/': typeof AuthenticatedFixturesIndexRoute
  '/veikkaa/': typeof AuthenticatedVeikkaaIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/futures': typeof AuthenticatedFuturesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/predictions': typeof AuthenticatedPredictionsRoute
  '/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/fixtures/$matchId': typeof AuthenticatedFixturesMatchIdRoute
  '/teams/$team': typeof AuthenticatedTeamsTeamRoute
  '/veikkaa/$matchId': typeof AuthenticatedVeikkaaMatchIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/fixtures': typeof AuthenticatedFixturesIndexRoute
  '/veikkaa': typeof AuthenticatedVeikkaaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fixtures': typeof AuthenticatedFixturesRouteWithChildren
  '/_authenticated/futures': typeof AuthenticatedFuturesRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/predictions': typeof AuthenticatedPredictionsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/fixtures/$matchId': typeof AuthenticatedFixturesMatchIdRoute
  '/_authenticated/teams/$team': typeof AuthenticatedTeamsTeamRoute
  '/_authenticated/veikkaa/$matchId': typeof AuthenticatedVeikkaaMatchIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
  '/_authenticated/fixtures/': typeof AuthenticatedFixturesIndexRoute
  '/_authenticated/veikkaa/': typeof AuthenticatedVeikkaaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/fixtures'
    | '/futures'
    | '/groups'
    | '/leaderboard'
    | '/predictions'
    | '/teams'
    | '/fixtures/$matchId'
    | '/teams/$team'
    | '/veikkaa/$matchId'
    | '/api/public/seed-admin'
    | '/fixtures/'
    | '/veikkaa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/futures'
    | '/groups'
    | '/leaderboard'
    | '/predictions'
    | '/teams'
    | '/'
    | '/fixtures/$matchId'
    | '/teams/$team'
    | '/veikkaa/$matchId'
    | '/api/public/seed-admin'
    | '/fixtures'
    | '/veikkaa'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/fixtures'
    | '/_authenticated/futures'
    | '/_authenticated/groups'
    | '/_authenticated/leaderboard'
    | '/_authenticated/predictions'
    | '/_authenticated/teams'
    | '/_authenticated/'
    | '/_authenticated/fixtures/$matchId'
    | '/_authenticated/teams/$team'
    | '/_authenticated/veikkaa/$matchId'
    | '/api/public/seed-admin'
    | '/_authenticated/fixtures/'
    | '/_authenticated/veikkaa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/predictions': {
      id: '/_authenticated/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof AuthenticatedPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/futures': {
      id: '/_authenticated/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof AuthenticatedFuturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fixtures': {
      id: '/_authenticated/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof AuthenticatedFixturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/veikkaa/': {
      id: '/_authenticated/veikkaa/'
      path: '/veikkaa'
      fullPath: '/veikkaa/'
      preLoaderRoute: typeof AuthenticatedVeikkaaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fixtures/': {
      id: '/_authenticated/fixtures/'
      path: '/'
      fullPath: '/fixtures/'
      preLoaderRoute: typeof AuthenticatedFixturesIndexRouteImport
      parentRoute: typeof AuthenticatedFixturesRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/veikkaa/$matchId': {
      id: '/_authenticated/veikkaa/$matchId'
      path: '/veikkaa/$matchId'
      fullPath: '/veikkaa/$matchId'
      preLoaderRoute: typeof AuthenticatedVeikkaaMatchIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/$team': {
      id: '/_authenticated/teams/$team'
      path: '/$team'
      fullPath: '/teams/$team'
      preLoaderRoute: typeof AuthenticatedTeamsTeamRouteImport
      parentRoute: typeof AuthenticatedTeamsRoute
    }
    '/_authenticated/fixtures/$matchId': {
      id: '/_authenticated/fixtures/$matchId'
      path: '/$matchId'
      fullPath: '/fixtures/$matchId'
      preLoaderRoute: typeof AuthenticatedFixturesMatchIdRouteImport
      parentRoute: typeof AuthenticatedFixturesRoute
    }
  }
}

interface AuthenticatedFixturesRouteChildren {
  AuthenticatedFixturesMatchIdRoute: typeof AuthenticatedFixturesMatchIdRoute
  AuthenticatedFixturesIndexRoute: typeof AuthenticatedFixturesIndexRoute
}

const AuthenticatedFixturesRouteChildren: AuthenticatedFixturesRouteChildren = {
  AuthenticatedFixturesMatchIdRoute: AuthenticatedFixturesMatchIdRoute,
  AuthenticatedFixturesIndexRoute: AuthenticatedFixturesIndexRoute,
}

const AuthenticatedFixturesRouteWithChildren =
  AuthenticatedFixturesRoute._addFileChildren(
    AuthenticatedFixturesRouteChildren,
  )

interface AuthenticatedTeamsRouteChildren {
  AuthenticatedTeamsTeamRoute: typeof AuthenticatedTeamsTeamRoute
}

const AuthenticatedTeamsRouteChildren: AuthenticatedTeamsRouteChildren = {
  AuthenticatedTeamsTeamRoute: AuthenticatedTeamsTeamRoute,
}

const AuthenticatedTeamsRouteWithChildren =
  AuthenticatedTeamsRoute._addFileChildren(AuthenticatedTeamsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFixturesRoute: typeof AuthenticatedFixturesRouteWithChildren
  AuthenticatedFuturesRoute: typeof AuthenticatedFuturesRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedPredictionsRoute: typeof AuthenticatedPredictionsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedVeikkaaMatchIdRoute: typeof AuthenticatedVeikkaaMatchIdRoute
  AuthenticatedVeikkaaIndexRoute: typeof AuthenticatedVeikkaaIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFixturesRoute: AuthenticatedFixturesRouteWithChildren,
  AuthenticatedFuturesRoute: AuthenticatedFuturesRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedPredictionsRoute: AuthenticatedPredictionsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedVeikkaaMatchIdRoute: AuthenticatedVeikkaaMatchIdRoute,
  AuthenticatedVeikkaaIndexRoute: AuthenticatedVeikkaaIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
